[package]
name = "crabwalk"
version = "0.1.0"
edition = "2021"

[registries.crates-io]
protocol = "sparse"

[dependencies]
actix-web = "4.3"
reqwest = { version = "0.11", features = ["json"] }
slack-hook = "0.8"
serde = { version = "1.0", features = ["derive"]}
log = "0.4"
env_logger = "0.10"
parking_lot = "0.12"
sha-1 = "0.10"
hmac = "0.12"
futures = "0.3"
hex = "0.4"
subtle = "2.5"
