[package]
name = "crabwalk"
version = "0.0.1"
edition = "2021"
default-run = "crabwalk"
license = "Apache-2.0"
publish = false

[[bin]]
doc = false
name = "crabwalk"
path = "src/main.rs"

[dependencies]
axum = "0.6.9"
tower-http = { version = "0.4.0", features = ["full"] }
tokio = { version = "1.25.0", features = ["full"]}
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
metrics = "0.20.1"
metrics-exporter-prometheus = "0.11.0"
