# .github/workflows/docker-publish.yml
name: Build and Publish Docker

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            platform: linux/amd64
          - target: aarch64-unknown-linux-gnu
            platform: linux/arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Add release tag
        id: release_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "::set-output name=RELEASE_VERSION::${GITHUB_REF#refs/tags/}"
          fi

      - name: docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            TARGET=${{ matrix.target }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ${{ steps.release_tag.outputs.RELEASE_VERSION != '' && 'ghcr.io/${{ github.repository }}:${{ steps.release_tag.outputs.RELEASE_VERSION }}' || '' }}
            ${{ steps.release_tag.outputs.RELEASE_VERSION != '' && 'ghcr.io/${{ github.repository }}:latest' || '' }}
          platforms: ${{ matrix.platform }}
          build-args: |
            VERSION=${{ github.ref }}
