# .github/workflows/docker-publish.yml
name: Build and Publish Docker

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/crabwalk:${{ github.sha }}
            ghcr.io/${{ github.repository }}/crabwalk:${{ github.ref }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ github.ref }}
